FBXExporter.exe warbear_binary.fbx warbear.azul
FBXExporter.exe buggy.fbx buggy.azul
FBXExporter.exe astroboy_binary.fbx astroboy.azul
FBXExporter.exe space_frigate.fbx space_frigate.azul
Vodka.exe warbear.azul warbear.blo -t VERTS_TYPE -n warbear
Vodka.exe buggy.azul buggy.blo -t VERTS_TYPE -n buggy
Vodka.exe astroboy.azul astroboy.blo -t VERTS_TYPE -n astroboy
Vodka.exe space_frigate.azul space_frigate.blo -t VERTS_TYPE -n space_frigate
Vodka.exe astroboy.tga astroboy_tex.blo -t TEXTURE_TYPE -n astroboy_tex
Vodka.exe buggy_diff.tga buggy_diff.blo -t TEXTURE_TYPE -n buggy_diff
Vodka.exe buggy_nrm.tga buggy_nrm.blo -t TEXTURE_TYPE -n buggy_nrm
Vodka.exe buggy_spec.tga buggy_spec.blo -t TEXTURE_TYPE -n buggy_spec
Vodka.exe polarbear.tga polar_tex.blo -t TEXTURE_TYPE -n polarbear
Vodka.exe warbear.tga warbear_tex.blo -t TEXTURE_TYPE -n warbear
Vodka.exe space_frigate.tga space_tex.blo -t TEXTURE_TYPE -n space_tex
Vodka.exe Crate.tga crate.blo -t TEXTURE_TYPE -n crate
Vodka.exe Duckweed.tga duckweed.blo -t TEXTURE_TYPE -n duckweed
Vodka.exe RedBrick.tga redbrick.blo -t TEXTURE_TYPE -n redbrick
Vodka.exe GrassRock.tga grocks.blo -t TEXTURE_TYPE -n grass
Vodka.exe Rocks.tga rocks.blo -t TEXTURE_TYPE -n rocks
Vodka.exe Sample_Flag.tga sample.blo -t TEXTURE_TYPE -n sampleflag
Vodka.exe Stone.tga stone.blo -t TEXTURE_TYPE -n stone
LIU.exe package.spu